### PR TITLE
CSS Compatibility with Vuematerial

### PR DESCRIPTION
**Pull request by abhimanusharma**
The styling will work with both bootstrap and vuematerial

### CODE REVIEW

**Comment by sethsandaru** [comment]
Hello @abhimanusharma ,

I will check this, thanks for your contribution!!

**Comment by abhimanusharma** [comment]
@sethsandaru Please merge this PR

**Comment by sethsandaru** [comment]
Hi @abhimanusharma 

I checked your commit. LGTM.

FYI: this will go to the branch v2.0.1. For me, it's like a patch release to improve the Vue Form Builder / Bug fixings.

**Review by sethsandaru — COMMENTED** [review]
LGTM

**Pull request merged**
